### ISSUE TITLE
Error loading transactions

### ISSUE THREAD

**Issue by lance-web3** [safe-global/safe-wallet-web#4063]
## Bug description
Error loading transactions on: http://UI_IP:8000/transactions/history?safe=dhobyghaut:0x74EcD5AAb9d8D0Fc709B031D487C5d2aFE9c1cC5

CGW error logs:
```
{"build_number":"40b1555","level":"error","message":{"chain_id":"90001","client_ip":"172.30.187.89","detail":"An error occurred","method":"GET","origin":null,"path":"/v1/chains/90001/safes/0x74EcD5AAb9d8D0Fc709B031D487C5d2aFE9c1cC5/transactions/history?trusted=false&imitation=false","response_time_ms":55.19123101234436,"route":"/v1/chains/:chainId/safes/:safeAddress/transactions/history","safe_app_user_agent":null,"status_code":500},"request_id":"5a5833a8-6b1f-4dc3-a946-4d71a093e754","timestamp":"2024-08-13T06:24:46.127Z","version":"v1.52.0"} 
```

TXS Service logs:
```
2024-08-13 06:26:08,037 MT::GET::api/v1/safes/<str:address>/all-transactions/::2::200::/txs/api/v1/safes/0x74EcD5AAb9d8D0Fc709B031D487C5d2aFE9c1cC5/all-transactions/
2024-08-13 06:26:08,062 [ERROR] [MainProcess] Internal Server Error: /txs/api/v1/safes/0x74EcD5AAb9d8D0Fc709B031D487C5d2aFE9c1cC5/creation/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/safe_transaction_service/history/views.py", line 970, in get
    safe_creation_info = SafeServiceProvider().get_safe_creation_info(address)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/safe_transaction_service/history/services/safe_service.py", line 111, in get_safe_creation_info
    parent_internal_tx = self._get_parent_internal_tx(creation_internal_tx)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/safe_transaction_service/history/services/safe_service.py", line 287, in _get_parent_internal_tx
    previous_trace = self.ethereum_tracing_client.tracing.get_previous_trace(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/gnosis/eth/ethereum_client.py", line 993, in get_previous_trace
    traces = reversed(self.trace_transaction(tx_hash))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/gnosis/eth/ethereum_client.py", line 1067, in trace_transaction
    return self.slow_w3.tracing.trace_transaction(tx_hash)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/web3/module.py", line 75, in caller
    result = w3.manager.request_blocking(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/web3/manager.py", line 330, in request_blocking
    return self.formatted_response(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/web3/manager.py", line 279, in formatted_response
    raise MethodUnavailable(
web3.exceptions.MethodUnavailable: {'code': -32601, 'message': 'the method trace_transaction does not exist/is not available'}
2024-08-13 06:26:08,091 MT::GET::api/v1/safes/<str:address>/creation/::51::500::/txs/api/v1/safes/0x74EcD5AAb9d8D0Fc709B031D487C5d2aFE9c1cC5/creation/
2024-08-13 06:26:08,168 MT::GET::api/v1/safes/<str:address>/multisig-transactions/::10::200::/txs/api/v1/safes/0x74EcD5AAb9d8D0Fc709B031D487C5d2aFE9c1cC5/multisig-transactions/
2024-08-13 06:26:08,297 MT::GET::api/v1/safes/<str:address>/messages/::3::200::/txs/api/v1/safes/0x74EcD5AAb9d8D0Fc709B031D487C5d2aFE9c1cC5/messages/
```

## Environment
 - Browser: Chrome

## Steps to reproduce
 1. Using default https://github.com/safe-global/safe-infrastructure/

## Expected result
Display transaction history without any errors

## Obtained result
![image](https://github.com/user-attachments/assets/35fb0978-7363-475f-8d71-755b75e3d0e4)

## Screenshots
![image](https://github.com/user-attachments/assets/c0f1080b-30d7-4e1b-b749-e0e024ee4028)

**Comment by katspaugh** [comment]
You're getting trace_transaction errors from the transaction service. Most likely you're not running a tracing node.
Please ask this question on Etherereum StackExchnage with a Safe tag. This repo is only for the frontend code.
